import { CourtSession, BookingProvider } from './types';
import { addHours } from 'date-fns';

const baseDate = new Date('2025-03-12T14:24:40+02:00');

export const mockProviders: BookingProvider[] = [
  {
    id: 'tennis-world',
    name: 'Tennis World',
    baseUrl: 'https://tennis-world.com',
    scrapingEnabled: true,
    apiEnabled: false,
  },
  {
    id: 'city-courts',
    name: 'City Courts',
    baseUrl: 'https://city-courts.com',
    scrapingEnabled: true,
    apiEnabled: true,
    apiKey: process.env.CITY_COURTS_API_KEY,
  },
];

export const mockSessions: CourtSession[] = [
  {
    id: '1',
    courtName: 'Central Park Tennis Club',
    location: 'Downtown Tennis Center',
    provider: 'tennis-world',
    bookingUrl: 'https://tennis-world.com/book/1',
    dateTime: addHours(baseDate, 1).toISOString(),
    duration: 60,
    price: 35.00,
    isRareFind: true,
    isLastMinute: false,
    isPromoted: true,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '2',
    courtName: 'Riverside Courts',
    location: 'Riverside Sports Complex',
    provider: 'city-courts',
    bookingUrl: 'https://city-courts.com/book/2',
    dateTime: addHours(baseDate, 2).toISOString(),
    duration: 90,
    price: 45.00,
    isRareFind: false,
    isLastMinute: true,
    isPromoted: false,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '3',
    courtName: 'Elite Tennis Academy',
    location: 'North Sports Center',
    provider: 'tennis-world',
    bookingUrl: 'https://tennis-world.com/book/3',
    dateTime: addHours(baseDate, 3).toISOString(),
    duration: 60,
    price: 40.00,
    isRareFind: false,
    isLastMinute: false,
    isPromoted: true,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '4',
    courtName: 'Community Tennis Club',
    location: 'West Park',
    provider: 'city-courts',
    bookingUrl: 'https://city-courts.com/book/4',
    dateTime: addHours(baseDate, 4).toISOString(),
    duration: 120,
    price: 60.00,
    isRareFind: true,
    isLastMinute: false,
    isPromoted: false,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '5',
    courtName: 'Indoor Tennis Center',
    location: 'East Side Mall',
    provider: 'tennis-world',
    bookingUrl: 'https://tennis-world.com/book/5',
    dateTime: addHours(baseDate, 2).toISOString(),
    duration: 30,
    price: 25.00,
    isRareFind: false,
    isLastMinute: true,
    isPromoted: true,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '6',
    courtName: 'Sunset Tennis Club',
    location: 'South Beach',
    provider: 'city-courts',
    bookingUrl: 'https://city-courts.com/book/6',
    dateTime: addHours(baseDate, 5).toISOString(),
    duration: 60,
    price: 38.00,
    isRareFind: true,
    isLastMinute: false,
    isPromoted: false,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '7',
    courtName: 'Mountain View Courts',
    location: 'Mountain Sports Complex',
    provider: 'tennis-world',
    bookingUrl: 'https://tennis-world.com/book/7',
    dateTime: addHours(baseDate, 6).toISOString(),
    duration: 90,
    price: 50.00,
    isRareFind: false,
    isLastMinute: false,
    isPromoted: true,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '8',
    courtName: 'Harbor Tennis Club',
    location: 'Harbor District',
    provider: 'city-courts',
    bookingUrl: 'https://city-courts.com/book/8',
    dateTime: addHours(baseDate, 3).toISOString(),
    duration: 120,
    price: 65.00,
    isRareFind: true,
    isLastMinute: true,
    isPromoted: false,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '9',
    courtName: 'University Tennis Center',
    location: 'University Campus',
    provider: 'tennis-world',
    bookingUrl: 'https://tennis-world.com/book/9',
    dateTime: addHours(baseDate, 4).toISOString(),
    duration: 60,
    price: 32.00,
    isRareFind: false,
    isLastMinute: true,
    isPromoted: true,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    id: '10',
    courtName: 'Lakeside Tennis Club',
    location: 'Lake Park',
    provider: 'city-courts',
    bookingUrl: 'https://city-courts.com/book/10',
    dateTime: addHours(baseDate, 7).toISOString(),
    duration: 90,
    price: 48.00,
    isRareFind: true,
    isLastMinute: false,
    isPromoted: false,
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
];
